#
# Copyright (C) 2019-2020 <wsdosh@gmail.com>
#
# This is free software, licensed under the Apache License, Version 3.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-webnavigation
LUCI_TITLE:=LuCI Support for webnavigation
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
#PKG_VERSION:=v0.0.1
PKG_LICENSE:=AGPL-3.0
PKG_MAINTAINER:=<https://github.com/doushang/luci-app-webnavigation>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
